### ISSUE TITLE
Fix random missing floor tiles

### ISSUE THREAD

**Issue by dhanvithnayak** [BAGUVIX456/The-Labyrinth#1]
Random floor tiles do not render. Most likely a bug in some script(s) in `Assets/Scripts/PCG`

**Comment by Akshat-Shu** [comment]
I'll be working on trying to fix this

**Comment by Akshat-Shu** [comment]
UPDATE: There is nothing wrong with the way floorTileMap is created. `Assets/Scripts/PCG` works just fine. Possible issue with rules in `Assets/TileSets`

**Comment by Akshat-Shu** [comment]
UPDATE: Identified the root cause, [line 21](https://github.com/BAGUVIX456/The-Labyrinth/blob/d9e24b571295b2e82ff2ff62f33e10377eaa7b33/Assets/Tilesets/Tiles/Floor.asset?plain=1#L21) should be removed since an empty sprite is picked randomly in some cases
