### ISSUE TITLE
Enemies not dealing damage when they should

### ISSUE THREAD

**Issue by Akshat-Shu** [BAGUVIX456/The-Labyrinth#12]
Even when player is in a close radius radius of the enemy, damage is not dealt to player since the Player object does not fall within the Attack point of the enemy. See clip for reference 

[Redefence Video](https://github.com/user-attachments/assets/f758648c-a6a1-4873-9c9c-27645dbdab07)

**Comment by YashSuthar983** [comment]
Hy i made a PR in which i fixed this issue .If anything else ,feel free to contact me
